CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_HEAP_MEM_POOL_SIZE=0
CONFIG_STACK_CANARIES=y

CONFIG_TEST_RANDOM_GENERATOR=y

CONFIG_CONSOLE=y
CONFIG_ASSERT=y
CONFIG_UART_LOG_LEVEL_DBG=y
CONFIG_SHELL_BACKEND_SERIAL=n

CONFIG_PM_DEVICE=y
CONFIG_SHELL=y
CONFIG_SHELL_VT100_COMMANDS=n
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FCB=y
CONFIG_ARM_MPU=y
CONFIG_HW_STACK_PROTECTION=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

CONFIG_THREAD_NAME=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_TRACING=y
CONFIG_TRACING_USER=y
CONFIG_TRACING_CTF=n
CONFIG_TRACING_BACKEND_UART=n
CONFIG_TRACING_ASYNC=n
CONFIG_TRACING_SYSCALL=n
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=y
CONFIG_LOG_BACKEND_SHOW_COLOR=n
CONFIG_LOG_PROCESS_THREAD=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_PROCESS_TRIGGER_THRESHOLD=1
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=0
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=10

CONFIG_RTC=y
CONFIG_RTC_ALARM=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_PRINTK=y

CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_GLIBCXX_LIBCPP=y

CONFIG_WATCHDOG=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_REBOOT=y
CONFIG_ADC=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_NEWLIB_LIBC=n
CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE=0
CONFIG_TIMESLICING=y
CONFIG_LOG_PREEMPTION_DELAY=y
CONFIG_LOG_EXECUTION_CYCLES=n
CONFIG_THREAD_STACK_INFO=y
